# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'biology_test/ui/AskForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(705, 425)
        font = QtGui.QFont()
        font.setPointSize(14)
        Form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/static/images/main.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 200))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.textEditAsk = QtWidgets.QTextEdit(self.groupBox)
        self.textEditAsk.setObjectName("textEditAsk")
        self.horizontalLayout.addWidget(self.textEditAsk)
        self.verticalLayout.addWidget(self.groupBox)
        self.widgetAnswers = QtWidgets.QWidget(Form)
        self.widgetAnswers.setObjectName("widgetAnswers")
        self.formLayout = QtWidgets.QFormLayout(self.widgetAnswers)
        self.formLayout.setObjectName("formLayout")
        self.verticalLayout.addWidget(self.widgetAnswers)
        self.pushButton = QtWidgets.QPushButton(Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("biology_test/ui/../../static/images/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(24, 24))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Тест - Ботаника"))
        self.groupBox.setTitle(_translate("Form", "Вопрос:"))
        self.textEditAsk.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans Serif\'; font-size:14pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'helvetica neue\'; font-size:16pt; color:#222222; background-color:#ffffff;\">В результате какого процесса образуются споры:</span></p></body></html>"))
        self.pushButton.setText(_translate("Form", "Продолжить"))
import biology_test.main_rc
